# Stolen from cbkadal's repo

title:       "Operating Systems 2021-1 (OS211)"
description: "Hello there!"
author:           "Hocky Yudhiono"
address:          "Pontianak"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://hockyy.github.io/os211/"
urlgithub:        "https://github.com/hockyy/os211/"
urlghpage:        "https://hockyy.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]
