# Stolen from cbkadal's repo

title:       "Operating Systems 2021-2 (OS212)"
description: "Hello there!"
author:           "Hocky Yudhiono"
address:          "Pontianak"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://hockyy.github.io/os212/"
urlgithub:        "https://github.com/hockyy/os212/"
urlghpage:        "https://hockyy.github.io/os212/"
keywords:         "jekyll, testing"
github:           [metadata]
